### ISSUE TITLE
redis_master and redis_slave should be dynamic inventory groups

### ISSUE THREAD

**Issue by bbaassssiiee** [dockpack/base_redis#5]
With Redis Sentinel, the inventory is dynamic in nature. You might define a certain host in your `[redis_master]` group, but the master role can be re-assigned automatically by the cluster hosts. Redis Sentinel re-writes the Sentinel config file.

So you might be surprised to login to the machine you thought was master and to find out this!!

```
redis-cli info replication
...
role:slave
master_host:10.1.1.20
...
```

Therefore, to make an idempotent role for a cluster, you will need to discover who is the master by probing hosts in the `[redis_server]` group (assuming you run sentinel on each). And then compose the groups with something like this:

```
 - name: get master_host
   run_once: true
   shell: "redis-cli info replication|grep -A1 role|tail -1|cut -d: -f2"
   register: master_host

 - name: add master_host
   add_host:
     name: "{{ master_host.stdout }}"
     groups: redis_master
```

https://stackoverflow.com/questions/31593210/dynamic-group-assignment-for-ansible-playbook/65888355#65888355
